# Данная опция отвечает за генерацию числа победителей.
# Генерация происходит от минимального до максимального числа (не включительно).
# Для данного числа победителей будет создано X рандомных точек времени в сутках.
winnersAmount:
  min: 1
  max: 5

# Опция для генерации рандомного числа.
# Можно использовать для команд награждения, например, пополнить баланс победителя на случайное число от min до max.
randomNumber:
  min: 1
  max: 5

# Здесь указываются команды, которые будут выполнены, когда наступит время X.
# В командах можно использовать плейсхолдеры %randomNumber% - случайное число, сгенерированное из опции выше
# и %winnerName% - ник случайного онлайн игрока, выбранного плагином, как победителя.
# Пример команды: /money give %winnerName% %randomNumber% - пополнить баланс случайного онлайн игрока на случайное количество валюты.
commandsToExecute:
  - ""

# Данная настройка отвечает за включение и отключения логов во время запуска плагина.
log:
  enabled: true
  howMuchWinners: "§eКол-во победителей: "
  timeToLottery: "§eВремя розыгрышей: "